version: 2.1

workflows:
  build-test:
    jobs:
      - build

jobs:
  # Generates a booster
  build:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies.
          command: yarn install
      - run:
          name: Generate a booster.
          command: node MTGBoosterGenerator.js ELD

            
